---
before_script:
    - git clone https://github.com/berndonline/cisco-lab-vagrant.git
    - cd cisco-lab-vagrant/
stages:
    - validate ansible
    - staging
validate:
    stage: validate ansible
    script:
        - bash ../linter.sh
staging:
    stage: staging
    script:
        - bash ../staging.sh
