---
- hosts: all
  connection: local
  user: vagrant
  gather_facts: 'no'
  tasks:
    - name: run show version on remote devices
      ios_command:
        commands: show version
      register: result
    - debug: msg={{ result }}
